version: '3'

volumes:
  postgres_data: {}
  static_data: {}
  media_data: {}

services:
  web:
    container_name: Isphera_web
    depends_on:
      - db
    build: .
    volumes:
      - .:/app/
      - static_data:/app/static/
      - media_data:/app/media/
    env_file: .env
    command: python manage.py runserver
    ports:
      - 8000:8000
    restart: always

  db:
    image: postgres:13.4-buster
    container_name: ISPHERA_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env
    environment:
      - DATABASE_URL: sqlite:///app/db
    restart: always

  redis:
    container_name: ${PROJECT_NAME}_redis
    image: redis:5.0
    restart: always
