# Generated by Django 5.1.3 on 2024-11-27 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_productinfotype_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='promocode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='common.promocode'),
        ),
    ]
